copy Release\MacType.dll "C:\Program Files\MacType\"
copy Release\MacType.pdb "C:\Program Files\MacType\"
copy Release\wow64ext.dll "C:\Program Files\MacType\"
copy x64\Release\MacType64.dll "C:\Program Files\MacType\"
copy x64\Release\MacType.pdb "C:\Program Files\MacType\MacType64.pdb"
copy deps\EasyHook\EasyHK*.dll "C:\Program Files\MacType\"
copy deps\EasyHook\EasyHK32.dll "C:\Program Files\MacType\EasyHook32.dll"
copy deps\EasyHook\EasyHK64.dll "C:\Program Files\MacType\EasyHook64.dll"